<?php
add_action('init', function() {
    register_post_type('auftraggeber', array(
        'labels' => array(
            'name' => 'Clients',
            'singular_name' => 'Client',
            'menu_name' => 'Clients',
            'all_items' => 'All Clients',
            'edit_item' => 'Edit Client',
            'view_item' => 'View Client',
            'view_items' => 'View Clients',
            'add_new_item' => 'Add New Client',
            'new_item' => 'New Client',
            'parent_item_colon' => 'Parent Client:',
            'search_items' => 'Search Clients',
            'not_found' => 'No clients found',
            'not_found_in_trash' => 'No clients found in Trash',
            'archives' => 'Client Archives',
            'attributes' => 'Client Attributes',
            'insert_into_item' => 'Insert into client',
            'uploaded_to_this_item' => 'Uploaded to this client',
            'filter_items_list' => 'Filter client list',
            'filter_by_date' => 'Filter clients by date',
            'items_list_navigation' => 'Client list navigation',
            'items_list' => 'Client list',
            'item_published' => 'Client published.',
            'item_published_privately' => 'Client published privately.',
            'item_reverted_to_draft' => 'Client reverted to draft.',
            'item_scheduled' => 'Client scheduled.',
            'item_updated' => 'Client updated.',
            'item_link' => 'Client Link',
            'item_link_description' => 'A link to a client.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-money',
        'supports' => array(
            'title',
            'editor',
            'thumbnail',
        ),
        'delete_with_user' => false,
    ));

    register_post_type('netzwerk-partner', array(
        'labels' => array(
            'name' => 'Network Partners',
            'singular_name' => 'Network Partner',
            'menu_name' => 'Network Partners',
            'all_items' => 'All Network Partners',
            'edit_item' => 'Edit Network Partner',
            'view_item' => 'View Network Partner',
            'view_items' => 'View Network Partners',
            'add_new_item' => 'Add New Network Partner',
            'new_item' => 'New Network Partner',
            'parent_item_colon' => 'Parent Network Partner:',
            'search_items' => 'Search Network Partners',
            'not_found' => 'No network partners found',
            'not_found_in_trash' => 'No network partners found in Trash',
            'archives' => 'Network Partner Archives',
            'attributes' => 'Network Partner Attributes',
            'insert_into_item' => 'Insert into network partner',
            'uploaded_to_this_item' => 'Uploaded to this network partner',
            'filter_items_list' => 'Filter network partner list',
            'filter_by_date' => 'Filter network partners by date',
            'items_list_navigation' => 'Network Partner list navigation',
            'items_list' => 'Network Partner list',
            'item_published' => 'Network Partner published.',
            'item_published_privately' => 'Network Partner published privately.',
            'item_reverted_to_draft' => 'Network Partner reverted to draft.',
            'item_scheduled' => 'Network Partner scheduled.',
            'item_updated' => 'Network Partner updated.',
            'item_link' => 'Network Partner Link',
            'item_link_description' => 'A link to a network partner.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-groups',
        'supports' => array(
            'title',
            'editor',
            'thumbnail',
        ),
        'delete_with_user' => false,
    ));

    register_post_type('project', array(
        'labels' => array(
            'name' => 'Projects',
            'singular_name' => 'Project',
            'menu_name' => 'Projects',
            'all_items' => 'All Projects',
            'edit_item' => 'Edit Project',
            'view_item' => 'View Project',
            'view_items' => 'View Projects',
            'add_new_item' => 'Add New Project',
            'new_item' => 'New Project',
            'parent_item_colon' => 'Parent Project:',
            'search_items' => 'Search Projects',
            'not_found' => 'No projects found',
            'not_found_in_trash' => 'No projects found in Trash',
            'archives' => 'Project Archives',
            'attributes' => 'Project Attributes',
            'insert_into_item' => 'Insert into project',
            'uploaded_to_this_item' => 'Uploaded to this project',
            'filter_items_list' => 'Filter project list',
            'filter_by_date' => 'Filter projects by date',
            'items_list_navigation' => 'Project list navigation',
            'items_list' => 'Project list',
            'item_published' => 'Project published.',
            'item_published_privately' => 'Project published privately.',
            'item_reverted_to_draft' => 'Project reverted to draft.',
            'item_scheduled' => 'Project scheduled.',
            'item_updated' => 'Project updated.',
            'item_link' => 'Project Link',
            'item_link_description' => 'A link to a project.',
        ),
        'public' => true,
        'hierarchical' => true,
        'show_in_rest' => true,
        'supports' => array(
            'title',
            'editor',
            'excerpt',
            'thumbnail',
        ),
        'delete_with_user' => false,
    ));

    register_post_type('sector', array(
        'labels' => array(
            'name' => 'Sectors',
            'singular_name' => 'Sector',
            'menu_name' => 'Sectors',
            'all_items' => 'All Sectors',
            'edit_item' => 'Edit Sector',
            'view_item' => 'View Sector',
            'view_items' => 'View Sectors',
            'add_new_item' => 'Add New Sector',
            'new_item' => 'New Sector',
            'parent_item_colon' => 'Parent Sector:',
            'search_items' => 'Search Sectors',
            'not_found' => 'No sectors found',
            'not_found_in_trash' => 'No sectors found in Trash',
            'archives' => 'Sector Archives',
            'attributes' => 'Sector Attributes',
            'insert_into_item' => 'Insert into sector',
            'uploaded_to_this_item' => 'Uploaded to this sector',
            'filter_items_list' => 'Filter sector list',
            'filter_by_date' => 'Filter sectors by date',
            'items_list_navigation' => 'Sector list navigation',
            'items_list' => 'Sector list',
            'item_published' => 'Sector published.',
            'item_published_privately' => 'Sector published privately.',
            'item_reverted_to_draft' => 'Sector reverted to draft.',
            'item_scheduled' => 'Sector scheduled.',
            'item_updated' => 'Sector updated.',
            'item_link' => 'Sector Link',
            'item_link_description' => 'A link to a sector.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-category',
        'supports' => array(
            'title',
            'editor',
            'thumbnail',
        ),
        'delete_with_user' => false,
    ));
});