<tr>
  <td>
    <table>
      <thead>
        <tr>
          <th>Laufrädergröße</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Vorne</td>
          <td>Hinten</td>
        </tr>
        <tr>
          <td>123</td>
          <td>234</td>
        </tr>
      </tbody>
    </table>
  </td>
</tr>
